In [1]:
import numpy as np 

In [30]:
arr = np.array([1,2,3,4,5,6,7,8,9])
arr_2 = np.array([10,11,12,13,14,15,16,17,18])

In [31]:
np.mean(arr)

np.float64(5.0)

In [32]:
np.std(arr)

np.float64(2.581988897471611)

In [33]:
np.var(arr)

np.float64(6.666666666666667)

In [34]:
np.min(arr)

np.int64(1)

In [35]:
np.max(arr)

np.int64(9)

In [36]:
np.sum(arr)

np.int64(45)

In [37]:
np.prod(arr)

np.int64(362880)

In [38]:
np.median(arr)

np.float64(5.0)

In [39]:
np.percentile(arr, 50)  # For the 50th percentile (median)

np.float64(5.0)

In [40]:
np.argmin(arr)

np.int64(0)

In [41]:
np.argmax(arr)

np.int64(8)

In [42]:
np.corrcoef(arr, arr_2)

array([[1., 1.],
       [1., 1.]])

In [43]:
np.unique(arr)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
np.diff(arr)

array([1, 1, 1, 1, 1, 1, 1, 1])

In [45]:
np.log(arr)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [46]:
np.exp(arr)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03])