# Indexing and slicing

In [10]:
import numpy as np 

In [11]:
arr = np.array([10, 20, 30, 40])
print(arr[0])  # 10
print(arr[-1]) # 40

10
40


# Slicing (Extracting Parts of an Array)

In [12]:
arr1 = arr[1:3]
print(arr1)

[20 30]


## Slicing returns a view, not a copy! Changes affect the original array.

In [16]:
arr2 = arr[1:3].copy()
arr2

array([20, 30])

# Fancy indexing

In [18]:
arr = np.array([10, 20, 30, 40])
indexes = [2,3]
arr[indexes]

array([30, 40])

# Boolean masking

In [19]:
arr = np.array([10, 20, 30, 40])
mask = arr>25
arr[mask]

array([30, 40])