## Mastering NUMPY

In [1]:
import numpy as np

In [3]:
arr = np.array([1,2,3])
arr

array([1, 2, 3])

In [13]:
# accessing the 2nd value , i.e index 1 
print(arr[1])

2


In [5]:
arr2 = np.array([[1,2,3] , [4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
# accessing the value "5", i.e at index 1,1 
print(arr2[1,1])

5


In [12]:
zero = np.zeros((3,3) , dtype = int)
zero

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [23]:
ones = np.ones((3,3),dtype = int)
ones

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [22]:
identity = np.identity(3 , dtype = int)
identity

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [25]:
eye_4x4 = np.eye(4 , dtype = int)
eye_4x4

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [26]:
# Shifting the diagonal with k parameter
# k=1 shifts diagonal above the main diagonal
upper_diag = np.eye(4, k=1)
upper_diag

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [27]:
# k=-1 shifts diagonal below the main diagonal
lower_diag = np.eye(4, k=-1)
lower_diag

array([[0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])